server:
  port: 8080

spring:
  application:
    name: akuflow

  datasource:
    url: jdbc:postgresql://localhost:16432/akuflow
    username: akuflow
    password: akuflow
  jpa:
    hibernate:
      #ddl-auto: update
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: false

temporal:
  connection:
    target: 127.0.0.1:7233
  namespace: default
  workers:
    - task-queue: akuflow-bpmn
      name: akuflow-bpmn-worker
      workflow-classes:
        - com.convertic.akuflow.temporal.workflows.BpmnWorkflowImpl
      activity-beans:
        - serviceTaskDispatcherActivitiesImpl
        - groovyScriptActivitiesImpl
        - definitionLookupActivitiesImpl
